### ISSUE TITLE
[MGS3] "Not Enough Image Data" error when trying to batch convert texture folder.

### ISSUE THREAD

**Issue by brad86m** [316austin316/CTXR-Converter#1]
I am trying to batch convert the main texture folder for MGS3. The one with over 10,000 files, but I am prompted with this error.
I would have to manually convert each file.

**Comment by KupaKodzilla** [comment]
There are caveats to this tool that aren't listed in the readme

Try using https://github.com/Jayveer/CtxrTool

**Comment by 316austin316** [comment]
> I am trying to batch convert the main texture folder for MGS3. The one with over 10,000 files, but I am prompted with this error. I would have to manually convert each file.

I'm not sure how you found the tool but if it's from the discord server i mentioned the error is solved by removing the problematic files and using single tga conversion with those, that should work fine. I will add some error handling that will tell us which file it is and skip it (or convert to .tga) but later.

**Comment by 316austin316** [comment]
> There are caveats to this tool that aren't listed in the readme
> 
> Try using https://github.com/Jayveer/CtxrTool

I updated the readme, not sure about the "caveats" but if there's anything more you want me to add let me know.
https://github.com/316austin316/CTXR-Converter#readme
also yes try javeer's tool he is great at mgs stuff

**Comment by KupaKodzilla** [comment]
> > I am trying to batch convert the main texture folder for MGS3. The one with over 10,000 files, but I am prompted with this error. I would have to manually convert each file.
> 
> I'm not sure how you found the tool but if it's from the discord server i mentioned the error is solved by removing the problematic files and using single tga conversion with those, that should work fine. I will add some error handling that will tell us which file it is and skip it (or convert to .tga) but later.

Your tool is listed under the thanks section on the following mod:

https://www.nexusmods.com/metalgearsolidmastercollection/mods/14

**Comment by brad86m** [comment]
Thanks for the replies. Yes, I can only get both tools working if I do files individually, which is not really feasible for so many files. 
I wanted to extract everything to be able to view the thumbnails and see what needs editing. 

The batch convert only allows png export, and not tga.

**Comment by 316austin316** [comment]
> Thanks for the replies. Yes, I can only get both tools working if I do files individually, which is not really feasible for so many files. I wanted to extract everything to be able to view the thumbnails and see what needs editing.
> 
> The batch convert only allows png export, and not tga.

this is why i mention to locate the problematic files, by my calculations, there is only a handful of files not working which are located in the image i attached. its just 15 files... locate these files and manually convert them. otherwise you can wait for the update im working on right now
![Capture](https://github.com/316austin316/CTXR-Converter/assets/115892533/31210079-4665-4ccc-87d8-b6a91721b1c5)

**Comment by brad86m** [comment]
> > Thanks for the replies. Yes, I can only get both tools working if I do files individually, which is not really feasible for so many files. I wanted to extract everything to be able to view the thumbnails and see what needs editing.
> > The batch convert only allows png export, and not tga.
> 
> this is why i mention to locate the problematic files, by my calculations, there is only a handful of files not working which are located in the image i attached. its just 15 files... locate these files and manually convert them. otherwise you can wait for the update im working on right now ![Capture](https://user-images.githubusercontent.com/115892533/279060650-31210079-4665-4ccc-87d8-b6a91721b1c5.PNG)

That's extremely helpful. Thank you.
