### ISSUE TITLE
File extensions aren't case-insensitive / get an error when trying to convert .PNG instead of .png

### ISSUE THREAD

**Issue by ShizCalev** [316austin316/CTXR-Converter#2]
![image](https://github.com/316austin316/CTXR-Converter/assets/6209658/447aea5c-24ec-42b4-a315-6471cfa4c0db)
case doesn't matter for file extensions in windows

**Comment by 316austin316** [comment]
new update on code should fix this issue, you can check now or wait until i have released new exe

**Comment by 316austin316** [comment]
updated the exe. issue should be fixed.
